language: node_js
node_js:
  - "6"

sudo: required
addons:
  - postgresql: "9.3"

services:
  - memcached
  - rabbitmq-server
  - redis-server

cache:
  directories:
    - node_modules

script:
  - npm run coverage
  
after_success:
  - npm run report-coverage
